#!/usr/bin/env python3
import sys

MOD = 5  # type: int


def solve(m: int):
    return


# Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    m = int(next(tokens))  # type: int
    solve(m)

if __name__ == '__main__':
    main()
