#!/usr/bin/env python3
import sys

    
global dp
dp = [[0]*1001 for i in range(10000)]


# Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    N, M = map(int, input.split())
    a = []
    b = []
    c = []
    for i in range(M):
        ax, bx = map(int, input().split())
        cx = map(int, input().split())
        a.append(ax)
        b.append(bx)
        c.append(cx)

    
    

if __name__ == '__main__':
    main()
