#!/usr/bin/env python3
import sys

MOD = 5  # type: int

def solve(N: int):
    N %= 30
    x = [1,2,3,4,5,6]
    for i in range(N):
        x[i%5], x[i%5+1] = x[i%5+1], x[i%5]

    print(''.join(map(str,x)))
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
