#!/usr/bin/env python3
import sys


def solve(n: int, a: "List[int]"):
    ans = 0
    for i in range(n):
        if(9 <= a[i] <= 10):
            ans += abs(a[i] - 9)
        elif(7 <= a[i] <= 8):
            ans += abs(a[i] - 7)
        elif(3 <= a[i] <= 6):
            ans += abs(a[i] - 3)
        elif(1 <= a[i] <= 2):
            ans += abs(a[i]-1)
    print(ans)
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    n = int(next(tokens))  # type: int
    a = [ int(next(tokens)) for _ in range(n) ]  # type: "List[int]"
    solve(n, a)

if __name__ == '__main__':
    main()
