#!/usr/bin/env python3
import sys


def solve(T: int, H: "List[int]", W: "List[int]"):
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    T = int(next(tokens))  # type: int
    H = [int()] * (T)  # type: "List[int]" 
    W = [int()] * (T)  # type: "List[int]" 
    for i in range(T):
        H[i] = int(next(tokens))
        W[i] = int(next(tokens))
    solve(T, H, W)

if __name__ == '__main__':
    main()
