#!/usr/bin/env python3
import sys

MOD = 10007  # type: int

def solve(n: int):
    if(n == 1 or n == 2):
        print(0)
        sys.exit()
    elif(n == 3):
        print(1)
        sys.exit()
    ans = [0]*(n+1)
    ans[3] = 1
    for i in range(4,n+1):
        ans[i] = (ans[i-1] + ans[i-2] + ans[i-3])%10007

    print(ans[n])
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    n = int(next(tokens))  # type: int
    solve(n)

if __name__ == '__main__':
    main()
