#!/usr/bin/env python3
import sys


def solve(S: str, N: int, l: "List[int]", r: "List[int]"):
    for i in range(N):
        S = S[:l[i]-1] + S[l[i]-1:r[i]][::-1] + S[r[i]:]

    print(S)
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    N = int(next(tokens))  # type: int
    l = [int()] * (N)  # type: "List[int]" 
    r = [int()] * (N)  # type: "List[int]" 
    for i in range(N):
        l[i] = int(next(tokens))
        r[i] = int(next(tokens))
    solve(S, N, l, r)

if __name__ == '__main__':
    main()
