#!/usr/bin/env python3
import sys


def solve(S: str, T: str):
    wc = 'atcoder'
    for i in range(len(S)):
        if(S[i] == T[i]):
            continue
        elif(S[i] == '@' or T[i] == '@'):
            if(S[i] in wc or T[i] in wc):
                continue
            else:
                break
        else:
            break
    else:
        print('You can win')
        sys.exit()
    
    print('You will lose')

    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)

if __name__ == '__main__':
    main()
