#!/usr/bin/env python3
import sys

YES = "YES"  # type: str
NO = "NO"  # type: str

def solve(N: int, a: int, b: int, K: int, P: "List[int]"):
    ans = [a,b] + P.copy()
    print(YES) if(len(ans) == len(list(set(ans)))) else print(NO)

    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    P = [ int(next(tokens)) for _ in range(K) ]  # type: "List[int]"
    solve(N, a, b, K, P)

if __name__ == '__main__':
    main()
