#!/usr/bin/env python3
import sys


def solve(N: int, g_A: int, s_A: int, b_A: int, g_B: int, s_B: int, b_B: int):
    return


# Generated by 1.1.3 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    g_A = int(next(tokens))  # type: int
    s_A = int(next(tokens))  # type: int
    b_A = int(next(tokens))  # type: int
    g_B = int(next(tokens))  # type: int
    s_B = int(next(tokens))  # type: int
    b_B = int(next(tokens))  # type: int
    solve(N, g_A, s_A, b_A, g_B, s_B, b_B)

if __name__ == '__main__':
    main()
