#!/usr/bin/env python3
import sys


def solve(K: int, N: int, v: "List[int]", w: "List[str]"):
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    v = [int()] * (N)  # type: "List[int]" 
    w = [str()] * (N)  # type: "List[str]" 
    for i in range(N):
        v[i] = int(next(tokens))
        w[i] = next(tokens)
    solve(K, N, v, w)

if __name__ == '__main__':
    main()
