#!/usr/bin/env python3
import sys


def solve(N: int):
    a1 = int(N/3600)
    a2 = int(N%3600/60)
    a3 = int(N%60)
    ans = str(a1).zfill(2) + ":" + str(a2).zfill(2) + ":" + str(a3).zfill(2)
    print(ans)
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
