#include <bits/stdc++.h>
using namespace std;


void solve(long long s){

}

// Generated by 1.1.3 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long s;
    scanf("%lld",&s);
    solve(s);
    return 0;
}
