#!/usr/bin/env python3



# Generated by 1.1.3 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    l = list(map(int,input().split()))
    l.sort()
    print(int(l[0]*l[1]/2))
    return 

if __name__ == '__main__':
    main()
