#!/usr/bin/env python3
import sys


def solve(n: int, X: int, a: "List[int]"):
    xl = format(X,'b')
    ans = 0
    for i,x in enumerate(reversed(xl)):
        if(x == '1'):
            ans += a[i]
    print(ans)
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    n = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    a = [ int(next(tokens)) for _ in range(n-1-0+1) ]  # type: "List[int]"
    solve(n, X, a)

if __name__ == '__main__':
    main()
