#!/usr/bin/env python3
import sys

# Generated by 1.1.5 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    N = int(input())
    F = [ [int(x) for x in input().split()] for i in range(N)]
    P = [ [int(x) for x in input().split()] for i in range(N)]

    ans = -10000000000000000
    for i in range(1,1<<10):
        pf = 0
        for j in range(N):
            c = 0
            for k in range(10):
                if(i & (1<<k)):
                    if(F[j][k]):
                        c += 1
            pf += P[j][c]

        ans = max(ans, pf)
        

    print(ans)

    pass

if __name__ == '__main__':
    main()
