#!/usr/bin/env python3
import sys


def solve(N: int, G: int, E: int, p: "List[int]", a: "List[int]", b: "List[int]"):
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    G = int(next(tokens))  # type: int
    E = int(next(tokens))  # type: int
    p = [ int(next(tokens)) for _ in range(G) ]  # type: "List[int]"
    a = [int()] * (E)  # type: "List[int]" 
    b = [int()] * (E)  # type: "List[int]" 
    for i in range(E):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    solve(N, G, E, p, a, b)

if __name__ == '__main__':
    main()
