#!/usr/bin/env python3
import sys


def solve(s: "List[int]", e: "List[int]"):
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = [int()] * (3)  # type: "List[int]" 
    e = [int()] * (3)  # type: "List[int]" 
    for i in range(3):
        s[i] = int(next(tokens))
        e[i] = int(next(tokens))
    solve(s, e)

if __name__ == '__main__':
    main()
