#!/usr/bin/env python3
import sys


def solve(N: int, K: int, a: "List[int]"):
    r = [0] * (N+5)
    for i in range(N):
        r[i+1] = r[i] + a[i]


    ans = 0
    for i in range(1, N-K+2):
        ans += r[i+K-1] - r[i-1]

    print(ans)
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, a)

if __name__ == '__main__':
    main()
