#!/usr/bin/env python3
import sys


def solve(s: str):
    N = len(s)
    
    for i in range(N-1):
        if(s[i] == s[i+1]):
            print(i+1, i+2)
            exit()
        else:
            if(i < N-2 and s[i] == s[i+2]):
                print(i+1, i+3)
                exit()
    
    print(-1,-1)

    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = next(tokens)  # type: str
    solve(s)

if __name__ == '__main__':
    main()
