#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str

import sys
from collections import deque

# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    H,W = map(int,input().split())
    maze = [input() for i in range(H)]
    d = [[False]*W for i in range(H)]

    sx = 0
    sy = 0
    for i in maze:
        if(i.find('s') != -1):
            sx = i.find('s')
            break
        else:
            sy += 1
    

    q = deque()

    q.append([sy, sx])
    # d[sy][sx] = True

    gx = 0
    gy = 0
    while(len(q)):
        ty,tx = q.pop()
        if(0 <= ty < H and 0 <= tx < W and maze[ty][tx] != '#' and d[ty][tx] == False):
            d[ty][tx] = True
            if(maze[ty][tx] == 'g'):
                gx = tx
                gy = ty
                print(YES)
                sys.exit()
            else:
                for i,j in [[1, 0], [0, 1], [-1, 0], [0, -1]]:
                    q.append([ty+j, tx+i])

    print(NO)

    

if __name__ == '__main__':
    main()
