#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]", b: "List[int]", r: "List[int]", K: int, y: "List[int]"):
    return


# Generated by 1.1.3 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int()] * (N)  # type: "List[int]" 
    b = [int()] * (N)  # type: "List[int]" 
    r = [int()] * (N)  # type: "List[int]" 
    for i in range(N):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
        r[i] = int(next(tokens))
    K = int(next(tokens))  # type: int
    y = [ int(next(tokens)) for _ in range(K) ]  # type: "List[int]"
    solve(N, a, b, r, K, y)

if __name__ == '__main__':
    main()
