#!/usr/bin/env python3
import sys

YES = "YES"  # type: str
NO = "NO"  # type: str

def solve(N: int, NG: "List[int]"):
    ng1, ng2, ng3 = sorted(NG)
    if (N > ng1 and ng2-ng1 == 1 and ng3-ng2 == 1) or (N in NG):
        print(NO)
        exit()

    c = 100
    while N > 0 and c > 0:
        if N-3 not in NG and N-3 >= 0:
            N -= 3
        elif N-2 not in NG and N-2 >= 0:
            N -= 2
        elif N-1 not in NG and N-1 >= 0:
            N -= 1
        else:
            print(NO)
            exit()
        c -= 1

    if N == 0:
        print(YES)
    else:
        print(NO)

    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    NG = [ int(next(tokens)) for _ in range(3) ]  # type: "List[int]"
    solve(N, NG)

if __name__ == '__main__':
    main()
