#!/usr/bin/env python3
import sys


def solve(N: int, D: int, K: int, L: "List[int]", R: "List[int]", S: "List[int]", T: "List[int]"):
    
    ans = [] 

    for i in range(K):
        p = S[i]
        for j in range(D):
            if L[j] <= p <= R[j]:
                if p < T[i]:
                    p = min(T[i], R[j])
                elif p > T[i]:
                    p = max(T[i], L[j])
                
            if p == T[i]:
                ans.append(j+1)
                break

    for i in ans:
        print(i)

    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    L = [int()] * (D)  # type: "List[int]" 
    R = [int()] * (D)  # type: "List[int]" 
    for i in range(D):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    S = [int()] * (K)  # type: "List[int]" 
    T = [int()] * (K)  # type: "List[int]" 
    for i in range(K):
        S[i] = int(next(tokens))
        T[i] = int(next(tokens))
    solve(N, D, K, L, R, S, T)

if __name__ == '__main__':
    main()
