#!/usr/bin/env python3
import sys


def solve(R: int, C: int, K: int, s: "List[str]"):
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    R = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    s = [ next(tokens) for _ in range(R) ]  # type: "List[str]"
    solve(R, C, K, s)

if __name__ == '__main__':
    main()
