#!/usr/bin/env python3
import sys


def solve(N: int, M: int):

    if M-2*N < 0 or M-2*N > 2*N:
        print('-1 -1 -1')
        exit()

    x,y,z = 0,0,0
    d = M-N*2
    x = N
    z = d//2
    x -= d//2
    d = d%2
    if d == 1:
        x -= 1
        y += 1

    print(x, y, z)


    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    solve(N, M)

if __name__ == '__main__':
    main()
