#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]"):
    def make_odd(x: int):
        if x%2 != 0:
            return x
        
        return make_odd(x//2)
    
    print(len(list(set([make_odd(i) for i in a]))))
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [ int(next(tokens)) for _ in range(N) ]  # type: "List[int]"
    solve(N, a)

if __name__ == '__main__':
    main()
